# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.4.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /mnt/LAB/rag-chat-poc/backend/.env:Z
    io.kubernetes.cri-o.SandboxID/rag-backend-container: 9082853d7d0fc22bc6ce348771766f37d57a9be2a1363a34d9f7462d1318491a
    io.kubernetes.cri-o.SandboxID/rag-frontend-container: 9082853d7d0fc22bc6ce348771766f37d57a9be2a1363a34d9f7462d1318491a
  creationTimestamp: "2025-03-28T21:09:19Z"
  labels:
    app: rag-poc-pod
  name: rag-poc-pod
spec:
  containers:
  - image: localhost/rag-chat-backend:0.1
    name: rag-backend-container
    ports:
    - containerPort: 8000
      hostPort: 8000
    - containerPort: 8501
      hostPort: 8501
    securityContext: {}
    volumeMounts:
    - mountPath: /app/../projects
      name: mnt-lab-rag-chat-poc-projects-host-0
      readOnly: true
    - mountPath: /app/.env
      name: mnt-lab-rag-chat-poc-backend-.env-host-1
      readOnly: true
  - image: localhost/rag-chat-frontend:0.1
    name: rag-frontend-container
    securityContext: {}
  volumes:
  - hostPath:
      path: /mnt/LAB/rag-chat-poc/projects
      type: Directory
    name: mnt-lab-rag-chat-poc-projects-host-0
  - hostPath:
      path: /mnt/LAB/rag-chat-poc/backend/.env
      type: File
    name: mnt-lab-rag-chat-poc-backend-.env-host-1

