# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.4.1
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-03-28T20:36:34Z"
  labels:
    app: rag-poc-pod
  name: rag-poc-pod
spec:
  ports:
  - name: "8000"
    nodePort: 32756
    port: 8000
    targetPort: 8000
  - name: "8501"
    nodePort: 31282
    port: 8501
    targetPort: 8501
  selector:
    app: rag-poc-pod
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.SandboxID/rag-frontend-container: c538af021ecf8cbec61840652f3e0584c38112809a00f8bf3d7c75a7cdb6f965
  creationTimestamp: "2025-03-28T20:36:34Z"
  labels:
    app: rag-poc-pod
  name: rag-poc-pod
spec:
  containers:
  - image: localhost/rag-chat-frontend:0.1
    name: rag-frontend-container
    ports:
    - containerPort: 8000
    - containerPort: 8501
    securityContext: {}

