# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.4.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /mnt/LAB/rag-chat-poc/projects:Z
    io.kubernetes.cri-o.SandboxID/rag-backend-container: f2849be5f310131f37fe264774c80d3c235a4530f5bed2d1c654383782f7d576
    io.kubernetes.cri-o.SandboxID/rag-frontend-container: f2849be5f310131f37fe264774c80d3c235a4530f5bed2d1c654383782f7d576
  creationTimestamp: "2025-03-28T20:51:00Z"
  labels:
    app: rag-poc-pod
  name: rag-poc-pod
spec:
  containers:
  - image: localhost/rag-chat-backend:0.1
    name: rag-backend-container
    ports:
    - containerPort: 8000
      hostPort: 8000
    - containerPort: 8501
      hostPort: 8501
    securityContext: {}
    volumeMounts:
    - mountPath: /app/.env
      name: mnt-lab-rag-chat-poc-backend-.env-host-0
      readOnly: true
    - mountPath: /app/../projects
      name: mnt-lab-rag-chat-poc-projects-host-1
  - image: localhost/rag-chat-frontend:0.1
    name: rag-frontend-container
    securityContext: {}
  volumes:
  - hostPath:
      path: /mnt/LAB/rag-chat-poc/backend/.env
      type: File
    name: mnt-lab-rag-chat-poc-backend-.env-host-0
  - hostPath:
      path: /mnt/LAB/rag-chat-poc/projects
      type: Directory
    name: mnt-lab-rag-chat-poc-projects-host-1
